### ISSUE TITLE
.dokkubuild inside repo is not considered

### ISSUE THREAD

**Issue by voronianski** [ignlg/dokku-builders-plugin#1]
Thanks for very helpful plugin! It's the best one for easy managing `bower` and `grunt`/`gulp` inside projects.

However it seems like bug here - `.dokkubuild` inside `/home/dokku/myapp` wasn't get by plugin. I was able to configure app with env variables then.

**Comment by ignlg** [comment]
Is the `.dokkubuild` file in your app root and in your git repository? It should be fetched from there.
